function getIcon(file, pathName) {
  const type = file === 'link' ? pathName.split('.').pop() : file
  switch (type) {
    case 'htm':
      return ''
    case 'html':
      return ''
    case 'css':
      return ""
    case 'sass':
      return ''
    case 'scss':
      return ''
    case 'less':
      return ''
    case 'md':
      return ''
    case 'mdx':
      return ''
    case 'markdown':
      return ''
    case 'rmd':
      return ''
    case 'json':
      return ''
    case 'vue':
      return '﵂'
    case 'js':
      return ''
    case 'ts':
      return ''
    case 'jsx':
      return ''
    case 'tsx':
      return ''
    case 'php':
      return ''
    case 'py':
      return ''
    case 'pyc':
      return ''
    case 'pyo':
      return ''
    case 'pyd':
      return ''
    case 'cpp':
      return ''
    case 'c+':
      return ''
    case 'cxx':
      return ''
    case 'cc':
      return ''
    case 'cp':
      return ''
    case 'c':
      return ''
    case 'go':
      return ''
    case 'lua':
      return ''
    case 'java':
      return ''
    case 'swift':
      return ''
    case 'sh':
      return ''
    case 'fish':
      return ''
    case 'bash':
      return ''
    case 'zsh':
      return ''
    case 'ksh':
      return ''
    case 'csh':
      return ''
    case 'awk':
      return ''
    case 'bashrc':
      return ''
    case 'zshrc':
      return ''
    case 'ps1':
      return ''
    case 'db':
      return ''
    case 'sql':
      return ''
    case 'conf':
      return ''
    case 'yml':
      return ''
    case 'yaml':
      return ''
    case 'gitignore':
      return ''
    case 'gitconfig':
      return ''
    case 'toml':
      return ''
    case 'makefile':
      return ''
    case 'jpg':
      return ''
    case 'jpeg':
      return ''
    case 'bmp':
      return ''
    case 'png':
      return ''
    case 'webp':
      return ''
    case 'gif':
      return ''
    case 'ico':
      return ''
    case 'android':
      return ''
    case 'npmrc':
      return ''
    case 'apk':
      return ''
    case 'apple':
      return ''
    case 'audio':
      return ''
    case 'avi':
      return ''
    case 'styl':
      return ''
    case 'license':
      return ''
    case 'LICENSE':
      return ''
    case 'dart':
      return ''
    case 'doc':
      return ''
    case 'docker':
      return ''
    case 'csv':
      return ''
    case 'dockerfile':
      return ''
    case 'docx':
      return ''
    case 'ebook':
      return ''
    case 'env':
      return ''
    case 'epub':
      return ''
    case 'exe':
      return ''
    case 'flv':
      return ''
    case 'font':
      return ''
    case 'jar':
      return ''
    case 'm4a':
      return ''
    case 'mkv':
      return ''
    case 'mobi':
      return ''
    case 'mov':
      return ''
    case 'mp3':
      return ''
    case 'mp4':
      return ''
    case 'ogg':
      return ''
    case 'ppt':
      return ''
    case 'pptx':
      return ''
    case 'ogv':
      return ''
    case 'otf':
      return ''
    case 'pdf':
      return ''
    case 'psd':
      return ''
    case 'rar':
      return ''
    case 'rss':
      return ''
    case 'svg':
      return ''
    case 'tar':
      return ''
    case 'ttf':
      return ''
    case 'txt':
      return ''
    case 'video':
      return ''
    case 'vim':
      return ''
    case 'vimrc':
      return ''
    case 'gvimrc':
      return ''
    case 'wav':
      return ''
    case 'webm':
      return ''
    case 'woff':
      return ''
    case 'woff2':
      return ''
    case 'xls':
      return ''
    case 'xlsx':
      return ''
    case 'xml':
      return ''
    case 'xul':
      return ''
    case 'zip':
      return ''
    case 'slim':
      return ''
    case 'haml':
      return ''
    case 'ejs':
      return ''
    case 'webmanifest':
      return ''
    case 'mjs':
      return ''
    case 'rb':
      return ''
    case 'gemspec':
      return ''
    case 'rake':
      return ''
    case 'coffee':
      return ''
    case 'mustache':
      return ''
    case 'hbs':
      return ''
    case 'ini':
      return ''
    case 'bat':
      return ''
    case 'twig':
      return ''
    case 'cs':
      return ''
    case 'h':
      return ''
    case 'hh':
      return ''
    case 'hpp':
      return ''
    case 'hxx':
      return ''
    case 'hs':
      return ''
    case 'lhs':
      return ''
    case 'nix':
      return ''
    case 'ml':
      return 'λ'
    case 'mli':
      return 'λ'
    case 'diff':
      return ''
    case 'dump':
      return ''
    case 'clj':
      return ''
    default:
      if(file === 'dir') {
        switch (pathName) {
          case '.git':
            return ''
          case 'node_modules':
            return ''
          case '.vscode':
            return ''
          case '.Trash':
            return ''
          case '.github':
            return ''
          case 'config':
            return ''
          case 'hidden':
            return ''
          default:
            return ''
        }
      } else if(file === 'link') {
        return ''
      } else {
        if(/.*_history$/.test(type)) {
          return ''
        }
        return ''
      }
  }
}


module.exports = getIcon
